MONGO_HOST_IP = '10.100.8.89'
MONGO_DATABASE_NAME = 'paper_db'
MONGO_COLLECTION_NAME = 'paper'
PARSCIT_CONTAINER_DATA_VOLUME_LOCATION_FOR_HOST = "/home/cs/Datasets/pars"
PARSCIT_CONTAINER_DATA_VOLUME_LOCATION_FOR_CONTAINER = "pars"
